import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Link from "next/link";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "IPC Section 302",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header className="bg-gray-800 text-white p-4 shadow-lg">
          <div className="container mx-auto flex justify-between items-center">
            <Link href="/" className="text-xl font-bold">
              MyApp
            </Link>
            <nav className="space-x-4">
              <Link href="/" className="hover:text-pink-500 transition-colors">
                Home
              </Link>
              <Link
                href="/about"
                className="hover:text-pink-500 transition-colors"
              >
                About
              </Link>
              <Link
                href="/contact"
                className="hover:text-pink-500 transition-colors"
              >
                Contact
              </Link>
              <Link
                href="/signin"
                className="hover:text-pink-500 transition-colors"
              >
                Sign In
              </Link>
            </nav>
          </div>
        </header>
        <main>{children}</main>
      </body>
    </html>
  );
}
